Add aria-label to resolve accessibility
vtex-apps/breadcrumb pull request #103
Opened 2023-11-09 12:49 UTC by luis-otavio

#### What problem is this solving?

- Adicionado a propriedade `aria-label` para melhorar a experiência e resolver os alertas de acessibilidade da regra que [links precisam ter um nome compreensível](https://dequeuniversity.com/rules/axe/4.7/link-name), apontados pelo Lighthouse.
- Adicionado o builder de messages para traduzir o texto do campo `aria-label` no componente [BaseBreadcrumb](https://github.com/vtex-apps/breadcrumb/compare/master...luis-otavio:breadcrumb:master#diff-fa57c40bd82326e019cfab275a80ba0932c8973435e9f2ffc8e53105dc843677).

#### How to test it?

[Workspace](https://www.samsclub.com.br/vinhos?workspace=accessibilityplp)

Executar teste no Lighthouse ou PageSpeed.

#### Screenshots or example usage:

Antes da edição:
![image](https://github.com/vtex-apps/breadcrumb/assets/12280996/4cc09fac-4f9e-44af-9d94-6b6a60e06edd)

Após a edição:
![image](https://github.com/vtex-apps/breadcrumb/assets/12280996/6cc27e5a-eed5-4efa-8235-a305d5c1b387)

2023-11-17 12:13 UTC, luis-otavio commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2023-11-17 12:14 UTC, luis-otavio commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2023-11-17 12:14 UTC, luis-otavio commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2024-05-24 18:28 UTC, GusGuerra approved these changes

2024-08-19 19:06 UTC, iago1501 requested changes
Actually, it's not necessary

2024-08-19 20:05 UTC, iago1501 approved these changes

2024-08-20 13:32 UTC, merged